export const config = {
    headers: {
        Accept: "application/x-www-form-urlencoded",
        "Content-Type": "application/x-www-form-urlencoded",
    },
    mockData: {
        businessDetails: {
            businessName: "Many Busy Hands",
        },
        draftJoblist: [
            {
                joblistId: "1293801287",
                jobTitle: "Grapes Picker",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Burwood 2134 NSW",
                payRange: "$20 per hour",
                workType: "",
                timeStamp: "12 days ago",
                status: "Draft",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.jpg",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "basic",
            },
        ],
        inactiveJoblist: [
            {
                joblistId: "1293801284",
                jobTitle: "Truck Driver",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                payRange: "$40 per hour",
                workType: "Casual",
                timeStamp: "7 hours ago",
                status: "inactive",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "premium",
            },
            {
                joblistId: "1293801288",
                jobTitle: "Lady In waiting",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                payRange: "",
                workType: "Casual",
                timeStamp: "11 days ago",
                status: "inactive",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "ultra",
            },
        ],
        activeJoblist: [
            {
                joblistId: "1293801283",
                jobTitle: "Cherry Picker!",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                payRange: "$25 - $35 per hour, more for the correct candidate",
                workType: "Casual",
                timeStamp: "just now",
                status: "Active",
                jobImageSrc: "@/assets/img/icons/grapes-picking.jpg",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "premium",
                jobSummary: "Job summary. <br /> Test Br",
                jobDescription: "Job Description.",
                candidates: {
                    favorite: [
                        {
                            firstName: "Chandra",
                            lastName: "Dewi",
                            age: "20",
                            introduction:
                                "I am a backpacker from Indonesia. Looking to earn for a living and enjoying australia.",
                            education:
                                "Bachelor of Arts, Western Sydney University, 2020-2022",
                            workExperience: [
                                "Waitress at Restaurant for 1 year",
                                "Cherry picker for 1 year",
                            ],
                            resume: "Resume/path/resume.pdf",
                            coverLetter: "coverletter/path/coverletter.pdf",
                            favorite: true,
                            emailAddress: "chandra.dewi@gmail.com",
                            phoneNumber: "+61 0488 123 456",
                        },
                        {
                            firstName: "Guide",
                            lastName: "Dion",
                            age: "25",
                            introduction:
                                "I am from Thailand. Looking to earn for a living and enjoying australia.",
                            education:
                                "Diploma of IT, Western Sydney University, 2020-2022",
                            workExperience: [
                                "Cherry picker for 1 year",
                                "Fruit packer for 1 year",
                            ],
                            resume: "Resume/path/resume.pdf",
                            coverLetter: "coverletter/path/coverletter.pdf",
                            favorite: true,
                            emailAddress: "guide.dion@gmail.com",
                            phoneNumber: "+61 0488 123 456",
                        },
                    ],
                    normal: [
                        {
                            firstName: "Fruit",
                            lastName: "Fresh",
                            age: "25",
                            introduction:
                                "I am from Thailand. Looking to earn for a living and enjoying australia.",
                            education:
                                "Diploma of IT, Western Sydney University, 2020-2022",
                            workExperience: [
                                "Cherry picker for 1 year",
                                "Fruit packer for 1 year",
                            ],
                            resume: "Resume/path/resume.pdf",
                            coverLetter: "coverletter/path/coverletter.pdf",
                            favorite: false,
                            emailAddress: "Fruit.Fresh@gmail.com",
                            phoneNumber: "+61 0488 123 456",
                        },
                    ],
                },
            },
            {
                joblistId: "1293801284",
                jobTitle: "Truck Driver",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                payRange: "$40 per hour",
                workType: "Casual",
                timeStamp: "7 hours ago",
                status: "Active",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "ultra",
                jobSummary: "Job summary. <br /> Test Br",
                jobDescription: "Job Description.",
            },
            {
                joblistId: "1293801285",
                jobTitle: "Farmer",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                payRange: "$20 per hour",
                workType: "Casual",
                timeStamp: "10 days ago",
                status: "Active",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "basic",
                jobSummary: "Job summary. <br /> Test Br",
                jobDescription: "Job Description.",
            },
            {
                joblistId: "1293801286",
                jobTitle: "Land Digger",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                payRange: "$23 per hour",
                workType: "Casual",
                timeStamp: "3 days ago",
                status: "Active",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "basic",
                jobSummary: "Job summary. <br /> Test Br",
                jobDescription: "Job Description.",
            },
            {
                joblistId: "1293801287",
                jobTitle: "Cleaner",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                payRange: "$20 per hour",
                workType: "Casual",
                timeStamp: "12 days ago",
                status: "Active",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "basic",
                jobSummary: "Job summary. <br /> Test Br",
                jobDescription: "Job Description.",
            },
            {
                joblistId: "1293801288",
                jobTitle: "Lady In waiting",
                businessName: "Western Sydney University Ltd",
                activity: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                payRange: "$20 per hour",
                workType: "Casual",
                timeStamp: "11 days ago",
                status: "Active",
                jobImageSrc:
                    "@/assets/img/Outback Australia Ringers having smoko.png",
                payRangeFrom: "25",
                payRangeTo: "28",
                adType: "basic",
                jobSummary: "Job summary. <br /> Test Br",
                jobDescription: "Job Description.",
            },
        ],
        invoiceList: [
            {
                id: 1,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 2,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 3,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 4,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 5,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 6,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 7,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 8,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 9,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 10,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 11,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 12,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 13,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 14,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 15,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 16,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 17,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 18,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 19,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 20,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 21,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 22,
                invoiceId: "INV1851386423",
                date: "25-10-2020",
                jobTitle: "Cherry Picker",
                location: "Sydney NSW 2000",
                price: "149.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 23,
                invoiceId: "INV1812312443",
                date: "12-1-2021",
                jobTitle: "Grape Picker",
                location: "Sydney NSW 2000",
                price: "249.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
            {
                id: 24,
                invoiceId: "INV9256892695",
                date: "18-4-2022",
                jobTitle: "Packer",
                location: "Sydney NSW 2000",
                price: "349.9",
                pdfPath: "@assets/pdf/path",
            },
        ],
    },
};
