export const config = {
    headers: {
        Accept: "application/x-www-form-urlencoded",
        "Content-Type": "application/x-www-form-urlencoded",
    },
    mockData: {
        businessDetails: {
            businessName: "Western Sydney University",
        },
        draftJoblist: [
            {
                joblistId: "1293801287",
                jobTitle: "Cleaner",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "",
                hourlyRate: "$20 per hour",
                workType: "",
                timeStamp: "12 days ago",
                status: "Draft",
            },
        ],
        disabledJoblist: [
            {
                joblistId: "1293801284",
                jobTitle: "Truck Driver",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                hourlyRate: "$40 per hour",
                workType: "Casual",
                timeStamp: "7 hours ago",
                status: "Disabled",
            },
            {
                joblistId: "1293801288",
                jobTitle: "Lady In waiting",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                hourlyRate: "",
                workType: "Casual",
                timeStamp: "11 days ago",
                status: "Disabled",
            },
        ],
        activeJoblist: [
            {
                joblistId: "1293801283",
                jobTitle: "Cherry Picker",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                hourlyRate:
                    "$25 - $35 per hour, more for the correct candidate",
                workType: "Casual",
                timeStamp: "just now",
                status: "Active",
            },
            {
                joblistId: "1293801284",
                jobTitle: "Truck Driver",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                hourlyRate: "$40 per hour",
                workType: "Casual",
                timeStamp: "7 hours ago",
                status: "Active",
            },
            {
                joblistId: "1293801285",
                jobTitle: "Farmer",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Sydney NSW 2000",
                hourlyRate: "$20 per hour",
                workType: "Casual",
                timeStamp: "10 days ago",
                status: "Active",
            },
            {
                joblistId: "1293801286",
                jobTitle: "Land Digger",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                hourlyRate: "$23 per hour",
                workType: "Casual",
                timeStamp: "3 days ago",
                status: "Active",
            },
            {
                joblistId: "1293801287",
                jobTitle: "Cleaner",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                hourlyRate: "$20 per hour",
                workType: "Casual",
                timeStamp: "12 days ago",
                status: "Active",
            },
            {
                joblistId: "1293801288",
                jobTitle: "Lady In waiting",
                businessName: "Western Sydney University Ltd",
                category: "Farming, Animals & Conservation",
                location: "Burwood NSW 2134",
                hourlyRate: "$20 per hour",
                workType: "Casual",
                timeStamp: "11 days ago",
                status: "Active",
            },
        ],
    },
};
